// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: App/service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Demo.App.Message {

  /// <summary>Holder for reflection information generated from App/service.proto</summary>
  public static partial class ServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for App/service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFBcHAvc2VydmljZS5wcm90bxIQRGVtby5BcHAuTWVzc2FnZRoRQXBwL21l",
            "c3NhZ2UucHJvdG8aGENvbW1vbi9jb21tTWVzc2FnZS5wcm90bzKgAQoLRGVt",
            "b1NlcnZpY2USSAoDU2F5Eh0uRGVtby5BcHAuTWVzc2FnZS5HcmVldGluZ01z",
            "ZxoiLkRlbW8uQXBwLk1lc3NhZ2UuR3JlZXRpbmdSZXNwb25zZRJHCg9UZXN0",
            "V2l0aFRlc3RNc2cSFC5EZW1vLkNvbW1vbi5UZXN0TXNnGh4uRGVtby5BcHAu",
            "TWVzc2FnZS5UZXN0UmVzcG9uc2VCE6oCEERlbW8uQXBwLk1lc3NhZ2ViBnBy",
            "b3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Demo.App.Message.MessageReflection.Descriptor, global::Demo.Common.CommMessageReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
